# -*- coding: utf-8 -*-
"""Customer Feedback.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GP_9i37bFfamlSZzub3jbYazCQ7NI0pm

<h3><b>Customer Feedback</b></h3>
"""

import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt

# Load the CSV file
df = pd.read_csv("https://drive.google.com/uc?id=152PxQK2sRREZlcW9fTaku8dyoipINeON", on_bad_lines='skip',engine='python', index_col=0)
df

# Apply sentiment analysis
df['sentiment_score'] = df['feedback_text'].apply(lambda x: TextBlob(x).sentiment.polarity)

df['sentiment_label'] = df['sentiment_score'].apply(
    lambda x: 'positive' if x > 0 else 'negative' if x < 0 else 'neutral'
)

# Display sentiment distribution
print(df['sentiment_label'].value_counts())

# Plot sentiment distribution
df['sentiment_label'].value_counts().plot(kind='bar',
                                          title='Customer Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Number of Feedbacks')
plt.show()

"""<p>
<b> Final Notes </b>
<ul>
<li>The company received more positives results than negatives. Their customers seem to be satisfied with the service and product. </li>
<li> It worths to assess what the negative feedback are about to identify areas of improvements.</li>
</p>
"""